### ISSUE TITLE
cross reference the Workflow Patterns repository

### ISSUE THREAD

**Issue by mr-c** [common-workflow-library/cwl-patterns#1]
http://www.workflowpatterns.com/patterns/

- [x] data patterns
- [x] control patterns
- [ ] resource patterns
- [ ] exception handling patterns
- [ ] presentation patterns
- [ ] event log imperfection patterns

- [ ] CWL examples for each supported pattern

**Comment by michael-kotliar** [comment]
**TODO**
Add information about features implemented by some platforms as of mid-2021. Add screenshots wherever it's possible.
